### ISSUE TITLE
Finetune Visual Bert pertained on COCO on VQA2

### ISSUE THREAD

**Issue by g-luo** [facebookresearch/mmf#621]
Hello! I'm trying to fine-tune visual bert on VQA2, but I'm getting this error: "Key input_ids not found in the SampleList"
![Screen Shot 2020-10-11 at 12 57 17 AM](https://user-images.githubusercontent.com/36020488/95673402-fcbbe080-0b5c-11eb-84bd-4171b02450fc.png)

Here are my config files:
[Archive.zip](https://github.com/facebookresearch/mmf/files/5360745/Archive.zip)

I was running the command: 
```
MMF_USER_DIR="." mmf_run config=./configs/other/vqa2.yaml\
        model=visual_bert \
        dataset=vqa2 \
        run_type=train_val \
        checkpoint.resume_pretrained=True \
        checkpoint.resume_zoo=visual_bert.pretrained.coco \
        training.num_workers=0
```

Thanks!

**Comment by vedanuj** [comment]
Hi can you paste a detailed error log?

**Comment by g-luo** [comment]
![Uploading Screen Shot 2020-10-11 at 3.54.07 PM.png…]()

**Comment by vedanuj** [comment]
You will need to override the `text_processor` to use `type: bert_tokenizer`. I can see you are doing that already in your configs. Make sure the indentations in the yaml file are proper and try again.

**Comment by g-luo** [comment]
Thanks so much! My issue was that I was missing 

```
processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
```

What is the difference between the processors defined in the dataset config vs the actual train_val config? It it that fields in the dataset config are using when MMF is building the database vs things in the train_val config are using in the training itself?

**Comment by g-luo** [comment]
@vedanuj I was also wondering if I could return bounding box info from VisualBERT on VQA2? I was looking through previous issues and it looks like if I add the following to the config it will work; could you confirm?

```
return_features_info: true
transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
```

Thanks!
