### ISSUE TITLE
Error registring custom loss module

### ISSUE THREAD

**Issue by skakar-git** [facebookresearch/mmf#905]
**Platform: Colab**

I am adding a custom loss module and getting this error:

`ValueError: No loss named custom_loss is registered to registry`

Following instructions, I am doing the following (sequentially in Colab cells):

(1) Register the model by running:

```
from mmf.common.registry import registry
import torch

@registry.register_loss("custom_loss")
class CustomLoss(torch.nn.Module):
  
  def __init__(self):
      super().__init__()
      
  def forward(self, sample_list, model_output):
    ...
```

(2) Change defaults.yaml to reflect:

```
model_config:
      vilbert:
        training_head_type: classification
        num_labels: 2
        losses:
        - custom_loss
```

(3) Train using mmf_run as usual.

Why is the loss module not being registered?
