### ISSUE TITLE
XLMRobertaTokenizer

### ISSUE THREAD

**Issue by hellowendy** [facebookresearch/mmf#909]
## ❓ Questions and Help
Is there a separate tokenizer for xlm-roberta-base? Or is roberta_tokenizer sufficient? Thanks!

**Comment by ytsheng** [comment]
Hi @hellowendy, thanks for using mmf:

Depends on your specific usecase, but in general, you can configure it like:
```
text_processor:
              type: roberta_tokenizer
              params:
                tokenizer_config:
                  type: xlm-roberta-base
                  params:
                    do_lower_case: true
                mask_probability: 0
                max_seq_length: 128
```
